title: Basic C Tutorial
description: Introductory C materials with executable examples
theme: jekyll-theme-cayman
markdown: kramdown
author: James Avery
kramdown:
  input: GFM
  syntax_highlighter: rouge
